language: python

python:
  - "3.6"

before_install:
  - pip install pipenv --upgrade

install:
  - pipenv install --dev
  - pipenv shell
  - cd src
  - cp CardsAgainstHumanity/settings/local.sample.env CardsAgainstHumanity/settings/local.env
  - python manage.py migrate

script:
  - python manage.py test
