version: "3.8"

services:
  app:
    image: havelantmate/cah:${APP_IMAGE_TAG}-dev
    container_name: "${PROJECT_NAME}_dev_app"
    environment:
      # App
      PORT: "${APP_PORT}"
    volumes:
      - ./app:/app
    working_dir: /app/src
#    command: ["go", "run", "main.go"]
#    command: ["CompileDaemon", "--build=\"go build -ldflags=\"-w -s\" -o /tmp/build/cardsagainst .\"", "--command=/tmp/build/cardsagainst"]
    command: ["fresh", "-c=/app/runner.conf"]
