version: "3.8"

services:
  app:
    labels:
      - "traefik.http.services.${PROJECT_NAME}_app.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.${PROJECT_NAME}_app.rule=Host(`${PROJECT_BASE_URL}`)"

  traefik:
    image: library/traefik:v2.3.4
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${TRAEFIK_HOST_PORT}:80"
      - "${TRAEFIK_DASHBOARD_HOST_PORT}:8080"
